# Site settings
title: KeJiShuCloud Blog
description: Technology changes life, a blog site that analyzes cutting-edge technology stacks
baseurl: "" 
url: "https://kejishucloud.github.io" # 网站的网址

# Social settings
twitter_username: kejishucloud
github_username: kejishucloud

# Build settings
markdown: kramdown
theme: minima

# Permalinks
permalink: /:categories/:year/:month/:day/:title:output_ext

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Kejishu Cloud"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Exclude from processing
exclude:
  - "node_modules"
  - "vendor/bundle"
  - "Gemfile.lock"
  - "package.json"
  - "yarn.lock"

# Google Analytics
google_analytics: G-JPTTDNCLWD

# Others
paginate: 5 # 每页显示的文章数
paginate_path: "/page:num"
